version: '3.8' # Specify the Docker Compose version

services:
  fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chardb-fe
    environment:
      - VITE_API_URL=/api
    ports:
      - "${APP_PORT}:80" # Map the container's port to the host
    depends_on:
      - be

  be:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chartdb-be
    environment:
      - MONGODB_URI=mongodb://root:example@db:27017
      - DB_NAME=chartdb
      - PORT=80

  db:
    image: mongodb/mongodb-community-server:latest
    container_name: chartdb-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017" 
    volumes:
      - db-data:/data/db


volumes:
  db-data: # Named volume for PostgreSQL persistence
